---
####### Stage ~/.docker/config.json
# name: '{{ ansible_name_module }} | file | Create local docker config directory'
# file:
#   path: "{{ local_home }}/.docker"
#   state: directory
# name: '{{ ansible_name_module }} | copy | Stage Quay.io Pull Secret to {{ local_home }}/.docker/config.json'
# copy:
#   src: "{{ dir_artifacts }}/.docker/master.json"
#   dest: "{{ local_home }}/.docker/config.json"
    
