---
- name: '{{ ansible_name_module }} | file | Create Directory Structure' 
  file:
    path: '{{ item }}'
    state: directory
    mode: '0644'
  with_items:
    - '{{ dir_secrets }}/cloudctl/ca/ssl'
