---
# Project Variables:
ccio_home: "{{ lookup('env','HOME') }}/.ccio"

# Localhost Environment 
local_path: "{{ lookup('env','PWD') }}"
local_home: "{{ lookup('env','HOME') }}"
local_user: "{{ lookup('env','USER') }}"

# CCIO Directory Vars
cciotree:
  - path: "{{ ccio_home }}"
    state: directory
  - path: "{{ ccio_home }}/run"
    state: directory
  - path: "{{ ccio_home }}/secrets"
    state: directory
  - path: "{{ ccio_home }}/pods"
    state: directory
  - path: "{{ ccio_home }}/profile.d"
    state: directory

# Ansible Playbook Run Variables
ansible_name: "ContainerCraft | CloudCtl Pod | {{ ansible_distribution }}"
sshkeys_pub: "{{ lookup('file', '{{ local_home }}/.ssh/id_rsa.pub') }}"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_python_interpreter: auto_silent

# play vars
pod_force_remove: true
container_uri_one: docker.io/containercraft/one:ccio
