---
- name: '{{ ansible_name_module }} | role:include_tasks | tree.yml' 
  include_tasks: tree.yml
- name: '{{ ansible_name_module }} | role:include_tasks | config.yml' 
  include_tasks: config.yml
- name: '{{ ansible_name_module }} | role:include_tasks | ssh.yml' 
  include_tasks: container.yml
