---
- name: '{{ ansible_name_module }} | cmd:podman.pod.rm | Podman purge {{ name_pod_cloudctl }}' 
  command:
    cmd: 'podman pod rm --force {{ name_pod_cloudctl }}'
# no_log: true
  ignore_errors: true
  when: pod_force_rm == true

- name: '{{ ansible_name_module }} | file:absent | Podman purge {{ name_pod_cloudctl }}' 
  file:
    path: '/tmp/cloudctl/{{ name_pod_cloudctl }}.pid'
    state: absent
  when: pod_force_rm == true

# Need to develop play kube method & dynamic jinja2 template defined pod
# name: '{{ ansible_name_module }} | cmd:podman.play.kube | Podman create CloudCtl' 
# command:
#   cmd: podman play kube /tmp/cloudctl/pod.yml

- name: '{{ ansible_name_module }} | cmd:podman.pod.create | Podman create {{ name_pod_cloudctl }}' 
  command:
    cmd:
     #podman pod create --replace
      podman pod create
        --publish 80:80
        --publish 443:443
        --publish 2022:2022
        --publish 6443:6443
        --publish 8082:8082
        --publish 8843:8443
        --publish 5000:5000
        --publish 5001:5001
        --publish 22623:22623
        --name {{ name_pod_cloudctl }}
        --hostname {{ name_pod_cloudctl }}
        --pod-id-file /tmp/cloudctl/{{ name_pod_cloudctl }}.pid
  args:
    creates: "/tmp/cloudctl/{{ name_pod_cloudctl }}.pid"
  register: cloudctl_pid
