---
- name: '{{ ansible_name_module }} | command:htpasswd.bcrypt | Generate Default Registry Basic Auth'
  command:
    cmd: 'htpasswd -Bbn cloudctl cloudctl'
  register: bcrypt_htpasswd

- name: '{{ ansible_name_module }} | copy:content.bcrypt_htpasswd | Generate Default Registry Basic Auth'
  copy:
    content: '{{ bcrypt_htpasswd.stdout }}'
    dest: /root/deploy/secrets/registry/auth/htpasswd
    mode: 0600

# Disabled due to no compatibile bcrypt algo for docker registry
# name: '{{ ansible_name_module }} | htpasswd | Generate Default Registry Basic Auth'
# htpasswd:
#   path: "{{ dir_deploy }}/secrets/registry/auth/htpasswd"
#   name: cloudctl
#   password: cloudctl
