#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ ansible_name }} | bundle | prep' 
  hosts: local
  connection: local
  vars_files:
    - '../p1.yml'
    - 'vars/global.yml'
    - 'vars/{{ target_environment }}.yml'
  vars:
    module: "upload"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    name_bucket: '{{ target_environment }}-{{ name_cluster_vpc }}-openshift-artifacts'
    cloud_key_id_special: "{{ lookup('ini', 'aws_access_key_id section=default file={{ dir_artifacts }}/.aws/govcloud.credentials') }}"
    cloud_key_secret_special: "{{ lookup('ini', 'aws_secret_access_key section=default file={{ dir_artifacts }}/.aws/govcloud.credentials') }}"
  tasks:

    - name: '{{ ansible_name_module }} | aws_s3 | Create AWS S3 Bucket: {{ name_cluster_vpc }}-{{ cluster_domain }}'
      aws_s3:
        bucket: '{{ name_cluster_vpc }}-{{ cluster_domain }}'
        region: '{{ cloud_region }}'
        mode: create
        aws_access_key: '{{ cloud_key_id_special }}'
        aws_secret_key: '{{ cloud_key_secret_special }}'
      ignore_errors: True

    - name: '{{ ansible_name_module }} | aws_s3 | Push Bundle to AWS S3 Bucket: {{ name_cluster_vpc }}-{{ cluster_domain }}' 
      aws_s3:
        mode: put
        bucket: '{{ name_cluster_vpc }}-{{ cluster_domain }}'
        region: '{{ cloud_region }}'
        object: '{{ cloud_provider }}-{{ target_environment }}-{{ name_cluster_vpc }}-p1bundle.tar'
        src: '{{ local_home }}/deploy/{{ cloud_provider }}-{{ target_environment }}-{{ name_cluster_vpc }}-p1bundle.tar'
        aws_access_key: '{{ cloud_key_id_special }}'
        aws_secret_key: '{{ cloud_key_secret_special }}'

