---
####### Self Signed Certs for registry
- name: '{{ ansible_name_module }} | file | Create Directory Structure' 
  file:
    path: '{{ item }}'
    state: directory
    mode: '0644'
  with_items:
    - /root/deploy/secrets/registry/ssl
    - /root/deploy/secrets/registry/auth

- name: '{{ ansible_name_module }} | openssl_privatekey | Registry Private Key'
  openssl_privatekey:
    path: "{{ dir_deploy }}/secrets/registry/ssl/registry.key"
    size: 4096

- name: '{{ ansible_name_module }} | openssl_csr | Registry Certificate Signing Request'
  openssl_csr:
    path: "{{ dir_deploy }}/secrets/registry/ssl/registry.csr"
    privatekey_path: "{{ dir_deploy }}/secrets/registry/ssl/registry.key"
    common_name: "registry"
    subject_alt_name:
      - "DNS:registry.*"
      - "DNS:localhost"
      - "DNS:cloudctl"
      - "IP:10.88.0.1"
      - "IP:10.0.1.1"

- name: '{{ ansible_name_module }} | openssl_certificate | Generate Default Registry Certificates | 365 Day TTL Self Signed'
  openssl_certificate:
    path: "{{ dir_deploy }}/secrets/registry/ssl/registry.crt"
    privatekey_path: "{{ dir_deploy }}/secrets/registry/ssl/registry.key"
    csr_path: "{{ dir_deploy }}/secrets/registry/ssl/registry.csr"
    selfsigned_not_after: "+365d"
    selfsigned_digest: "sha256"
    provider: selfsigned

- name: '{{ ansible_name_module }} | file | Create Directory Structure' 
  file:
    path: '{{ item }}'
    state: directory
    mode: '0644'
  with_items:
    - /root/deploy/secrets/ssh

- name: '{{ ansible_name_module }} | openssh_keypair | gen ssh keys'
  openssh_keypair:
    path: "{{ dir_deploy }}/secrets/ssh/id_rsa_cloudctl"
    comment: "core@cloudctl"
